# Generated by Django 4.1.3 on 2022-11-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
