# Generated by Django 4.1.3 on 2022-11-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0003_topic_article_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
