# Generated by Django 4.1.3 on 2022-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0004_remove_article_topic_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
