# Generated by Django 4.1.3 on 2022-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0005_article_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_feed', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(default='General', max_length=50)),
            ],
        ),
    ]
